### ISSUE TITLE
loading image without file

### ISSUE THREAD

**Issue by LordMZTE** [Hkattelu/Asciify#1]
I want to asciify an image that is in ram and not in a file. I have a DynamicImage ready, and this library's code looks like it can easily handle it, however with the current code (version 0.1.4), I see no way that this is possible.

**Comment by LordMZTE** [comment]
#2 fixes this and has some other improvements

**Comment by Hkattelu** [comment]
Thanks for the fix. I'll push the updated version to crates once your fix is in.
